name       : ntfs-3g
version    : 2021.8.22
release    : 13
source     :
    - https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2021.8.22.tgz : 55b883aa05d94b2ec746ef3966cb41e66bed6db99f22ddd41d1b8b94bb202efb
homepage   : https://github.com/tuxera/ntfs-3g/wiki
license    : GPL-2.0-or-later
component  : system.utils
summary    : Open source, driver for Windows NTFS file system
description: |
    Open source, driver for Windows NTFS file system. This can mount Windows partitions so that they are writeable and allows you edit or delete Windows files from Linux.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
setup      : |
    %configure --disable-static \
               --disable-ldconfig \
               --enable-posix-acls \
               --with-fuse=external
build      : |
    %make
install    : |
    %make_install rootbindir=/usr/bin rootlibdir=%libdir%
    rm -rvf $installdir/usr/share/doc
    ln -sv /usr/bin/ntfs-3g $installdir/sbin/mount.ntfs
