name        : ntfs-3g
homepage    : http://www.tuxera.com/community/ntfs-3g-download/
version     : 2016.2.22
release     : 8
source     :
    - https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2016.2.22.tgz : d7b72c05e4b3493e6095be789a760c9f5f2b141812d5b885f3190c98802f1ea0
license     :
    - GPL-2.0
summary     : Open source, driver for Windows NTFS file system
component   : system.utils
description : |
    Open source, driver for Windows NTFS file system. This can mount Windows partitions so that they are writeable and allows you edit or delete Windows files from Linux.
builddeps  :
    - pkgconfig(fuse)
    - acl-devel
    - attr-devel
setup      : |
    %configure --disable-static \
               --disable-ldconfig \
               --enable-posix-acls \
               --with-fuse=external
build      : |
    %make
install    : |
    %make_install rootbindir=/usr/bin rootlibdir=%libdir%
    rm -rvf $installdir/usr/share/doc
    ln -sv /usr/bin/ntfs-3g $installdir/sbin/mount.ntfs
