name        : ntfs-3g
homepage    : http://www.tuxera.com/community/ntfs-3g-download/
version     : 2015.3.14
release     : 7
source     :
    - https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2015.3.14.tgz : 97f996015d8316d4a272bd2629978e5e97072dd3cc148ce39802f8037c6538f2
license     :
    - GPL-2.0
summary     : Open source, driver for Windows NTFS file system
description : |
    Open source, driver for Windows NTFS file system. This can mount Windows partitions so that they are writeable and allows you edit or delete Windows files from Linux.
builddeps  :
    - pkgconfig(fuse)
setup      : |
    %configure --disable-static \
               --disable-ldconfig \
               --enable-posix-acls \
               --with-fuse=external
build      : |
    %make
install    : |
    %make_install rootbindir=/usr/bin rootlibdir=%libdir%
    rm -rvf $installdir/usr/share/doc
    ln -sv /usr/bin/ntfs-3g $installdir/sbin/mount.ntfs
