name        : ntfs-3g
version     : 2014.2.15
release     : 3
source      :
    - http://tuxera.com/opensource/ntfs-3g_ntfsprogs-2014.2.15.tgz : 4c3099400cb14b231a3c9d718b3a8d152d38555059341ce5fc6d02292a4a5b56
homepage    : http://www.tuxera.com/community/ntfs-3g-download/
license     :
    - GPL-2.0
summary     : Open source, driver for Windows NTFS file system
description : |
    Open source, driver for Windows NTFS file system. This can mount Windows partitions so that they are writeable and allows you edit or delete Windows files from Linux.
setup      : |
    %configure --disable-static \
               --disable-ldconfig

build      : |
    %make
install    : |
    %make_install rootlibdir=%libdir%
