name       : ntfs-3g
version    : 2022.10.3
release    : 16
source     :
    - https://tuxera.com/opensource/ntfs-3g_ntfsprogs-2022.10.3.tgz : f20e36ee68074b845e3629e6bced4706ad053804cbaf062fbae60738f854170c
homepage   : https://github.com/tuxera/ntfs-3g/wiki
license    : GPL-2.0-or-later
component  : system.utils
summary    : Open source, driver for Windows NTFS file system
description: |
    Open source, driver for Windows NTFS file system. This can mount Windows partitions so that they are writeable and allows you edit or delete Windows files from Linux.
builddeps  :
    - pkgconfig(fuse)
    - pkgconfig(libacl)
    - pkgconfig(libattr)
setup      : |
    %configure --disable-static \
               --disable-ldconfig \
               --enable-posix-acls \
               --with-fuse=external
build      : |
    %make
install    : |
    %make_install rootbindir=/usr/bin rootlibdir=%libdir%
    rm -rvf $installdir/usr/share/doc
    ln -sv /usr/bin/ntfs-3g $installdir/sbin/mount.ntfs
